services:
  - type: web
    name: ecommerce-app
    env: node
    buildCommand: |
      npm install
      npm run build
      npm run postbuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    plan: free
